GITLAB-K8S-62: Add Linkerd sidecar for Prod. US
AdaSupport/preview pull request #39
Opened 2020-10-07 16:28 UTC by RajsimmanRavi

Same as https://github.com/AdaSupport/uploader/pull/8/files

2020-10-08 09:02 UTC, aisrael approved these changes

2020-10-13 10:00 UTC, kzap requested changes

2020-10-13 10:00 UTC, kzap commented on _infra/manifests/ingress.yaml
> +      {{- end }}
same as other ingress, if linkerd is false then this will be an empty yaml and might fail, should probably add the open tracing snippet here also

2020-10-15 15:42 UTC, RajsimmanRavi commented on _infra/manifests/ingress.yaml
> +      {{- end }}
Yep, my bad! Updated it

2020-10-15 15:47 UTC, kzap approved these changes

2020-10-15 16:19 UTC, merged